### ISSUE TITLE
Unable to flash BBB with new images.

### ISSUE THREAD

**Issue by viteo** [ungureanuvladvictor/BBBlfs#28]
Im successfully flashing BBB with 3.8 kernel image from official beaglebone site, but with newest images with 4.1 kernel after flashing, bbb doesn't boot and none of leds is blinking. Please give some suggestions.

**Comment by viteo** [comment]
solved with robert nelson's usb-flasher scripts.

**Comment by Sarcasm** [comment]
@viteo : Can you share the link to these usb-flasher scripts?

**Comment by viteo** [comment]
https://github.com/RobertCNelson/boot-scripts/tree/master/tools/eMMC
